baseURL = "https://devops-brazil.github.io/OnWeb/"
languageCode = "en-us"
title = "DevOps Brazil"
theme = "hugo-business-frontpage-theme"
publishDir = "docs"
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "DevOps Brazil"
    description = "DevOps Brazil"

    [params.navbar]
        name = "DevOps Brazil"
        url = "https://devops-brazil.github.io/OnWeb/"

        [[params.navbar.nav]]
        current = true
        name = "Home"
        url = "#"
        [[params.navbar.nav]]
        name = "Vagas"
        url = "https://github.com/DevOps-Brazil/Vagas/issues"

    [params.header]
        name = "DevOps Brazil"
        tagline = '"pass on what you have learned"'

    # [params.summary]
    #     url = "#"

    #     [params.summary.description]

    #     [[params.summary.description.items]]
    #     description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. A deserunt neque tempore recusandae animi soluta quasi? Asperiores rem dolore eaque vel, porro, soluta unde debitis aliquam laboriosam. Repellat explicabo, maiores!"
    #     [[params.summary.description.items]]
    #     description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis optio neque consectetur consequatur magni in nisi, natus beatae quidem quam odit commodi ducimus totam eum, alias, adipisci nesciunt voluptate. Voluptatum."


    #     [params.summary.contact]
    #     name = "Start Bootstrap"
    #     address1 = "3481 Melrose Place"
    #     address2 = "Beverly Hills, CA 90210"
    #     phone = "(123) 456-7890"
    #     email = "name@example.com"

    # [params.projects]

    #     [[params.projects.sections]]
    #     # title = "Section 1"
    #     [[params.projects.sections.rows]]
    #     # title = "Section 1, Row 1"
    #     [[params.projects.sections.rows.items]]
    #     title = "Card title 1"
    #     description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus."
    #     url = "#"
    #     image = "300x200.png"
    #     [[params.projects.sections.rows.items]]
    #     title = "Card title 2"
    #     description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus totam ut praesentium aut."
    #     url = "#"
    #     image = "300x200.png"
    #     [[params.projects.sections.rows.items]]
    #     title = "Card title 3"
    #     description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque."
    #     url = "#"
    #     image = "300x200.png"
    #     [[params.projects.sections.rows]]
    #     # title = "Section 1, Row 2"
    #     [[params.projects.sections.rows.items]]
    #     title = "Card title 4"
    #     description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus."
    #     url = "#"
    #     image = "300x200.png"
    #     [[params.projects.sections.rows.items]]
    #     title = "Card title 5"
    #     description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus totam ut praesentium aut."
    #     url = "#"
    #     image = "300x200.png"

    #     [[params.projects.sections]]
    #     # title = "Section 2"
    #     [[params.projects.sections.rows]]
    #     # title = "Section 2, Row 1"
    #     [[params.projects.sections.rows.items]]
    #     title = "Card title 1"
    #     description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus."
    #     url = "#"
    #     image = "300x200.png"
    #     [[params.projects.sections.rows.items]]
    #     title = "Card title 2"
    #     description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus totam ut praesentium aut."
    #     url = "#"
    #     image = "300x200.png"
    #     [[params.projects.sections.rows.items]]
    #     title = "Card title 3"
    #     description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque."
    #     url = "#"
    #     image = "300x200.png"
    #     [[params.projects.sections.rows]]
    #     # title = "Section 2, Row 2"
    #     [[params.projects.sections.rows.items]]
    #     title = "Card title 4"
    #     description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus."
    #     url = "#"
    #     image = "300x200.png"

    [params.footer]
        copyright = "DevOps Brazil"